source 'http://rubygems.org'

gem 'rake'
gem 'sinatra'

gem 'slim'
gem 'compass', '~> 0.13.alpha.0'
gem 'coffee-script'
gem 'therubyracer'
gem 'sprockets'
gem 'uglifier'

gem 'redcarpet'
gem 'pygmentize'
gem 'albino'
